# Добавлен манифест для создания namespace
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diploma-app
  namespace: app # Добавлен namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diploma-app
  template:
    metadata:
      labels:
        app: diploma-app
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: nginx
        image: aaborovik/diploma-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: diploma-app-service
  namespace: app # Добавлен namespace
spec:
  type: NodePort
  selector:
    app: diploma-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
