---
- name: Install Helm
  hosts: masters[0]
  become: true
  vars:
    helm_version: "v3.14.0" # желаемая версия Helm
    helm_install_dir: "/usr/local/bin"
    helm_download_url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    temp_dir: "/tmp/helm"

  tasks:
  - name: Ensure temporary directory exists
    ansible.builtin.file:
      path: "{{ temp_dir }}"
      state: directory
      mode: '0755'

  - name: Download Helm archive
    ansible.builtin.get_url:
      url: "{{ helm_download_url }}"
      dest: "{{ temp_dir }}/helm.tar.gz"
      mode: '0644'
    retries: 3
    delay: 5

  - name: Extract Helm archive
    ansible.builtin.unarchive:
      src: "{{ temp_dir }}/helm.tar.gz"
      dest: "{{ temp_dir }}"
      remote_src: true
      extra_opts:
      - --strip-components=1
      creates: "{{ temp_dir }}/extracted/helm"

  - name: Install Helm binary
    ansible.builtin.copy:
      src: "{{ temp_dir }}/helm"
      dest: "{{ helm_install_dir }}/helm"
      mode: '0755'
      remote_src: true

  - name: Verify Helm installation
    ansible.builtin.command: helm version --short
    register: helm_check
    changed_when: false
    failed_when: helm_check.rc != 0

  - name: Cleanup temporary files
    ansible.builtin.file:
      path: "{{ temp_dir }}"
      state: absent
