#cloud-config
users:
- name: lex
  groups: sudo
  shell: /bin/bash
  sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]

  ssh_authorized_keys:
  - ${ssh_key}

package_update: true
package_upgrade: true

packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg
- lsb-release
- net-tools
- htop
- tmux
- python3
- python3-distutils

