name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
    - 'docker/nginx.conf'
    - 'docker/nginx-app.dockerfile'
    - 'docker/page/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Нужно для получения истории коммитов

    - name: Determine changed files
      id: changed-files
      run: |
        # Получаем список измененных файлов
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Changed files: $CHANGED_FILES"

        # Определяем, какие из нужных нам файлов изменились
        CHANGED_NGINX_CONF=false
        CHANGED_DOCKERFILE=false
        CHANGED_PAGE=false

        if [[ "$CHANGED_FILES" == *"docker/nginx.conf"* ]]; then
          CHANGED_NGINX_CONF=true
        fi

        if [[ "$CHANGED_FILES" == *"docker/nginx-app.dockerfile"* ]]; then
          CHANGED_DOCKERFILE=true
        fi

        if echo "$CHANGED_FILES" | grep -q "page/"; then
          CHANGED_PAGE=true
        fi

        # Формируем тег на основе изменений
        TAG_SUFFIX=""
        if [[ "$CHANGED_NGINX_CONF" == "true" ]]; then
          TAG_SUFFIX="changed-nginx.conf"
        elif [[ "$CHANGED_DOCKERFILE" == "true" ]]; then
          TAG_SUFFIX="changed-dockerfile"
        elif [[ "$CHANGED_PAGE" == "true" ]]; then
          TAG_SUFFIX="changed-page"
        else
          # Если по каким-то причинам попали сюда, хотя триггер был по paths
          TAG_SUFFIX="other-changes"
        fi

        echo "TAG_SUFFIX=$TAG_SUFFIX" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./docker
        file: ./docker/nginx-app.dockerfile
        push: true
        tags: |
          ${{ vars.REGISTRY }}:${{ steps.changed-files.outputs.TAG_SUFFIX }}
