name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'docker/**'
      - 'app/**'

jobs:
  deploy:
    if: |
      startsWith(github.ref, 'refs/tags/v') &&
      github.ref_name == 'main' &&
      (
        contains(github.event.head_commit.modified, 'docker/') ||
        contains(github.event.head_commit.modified, 'app/')
      )
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Установка Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Аутентификация в Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Определение тега образа
    - name: Extract Docker tag
      id: extract-tag
      run: |
        TAG="${GITHUB_REF#refs/tags/}"
        echo "TAG=${TAG}" >> $GITHUB_ENV
        echo "Using TAG: ${TAG}"

    # Сборка и отправка образа
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./docker
        file: ./docker/nginx-app.dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/diploma-nginx-app:${{ env.TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/diploma-nginx-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # # Настройка kubectl
    # - name: Set up Kubernetes
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'v1.30.0'

    # # Конфигурация доступа к кластеру
    # - name: Configure kubeconfig
    #   run: |
    #     mkdir -p ~/.kube
    #     echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
    #     kubectl cluster-info

    # # Деплой в Kubernetes
    # - name: Deploy to Kubernetes
    #   env:
    #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #   run: |
    #     envsubst < app/app-deployment.yml | kubectl apply -f -