name: Deploy to Kubernetes

on:
  push:
    tags:
      - 'v*' # Срабатывает при создании тега вида v1.0.0
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'app/**' # Добавлен путь к манифестам

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker tag
      id: tag
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "TAG=latest" >> $GITHUB_ENV
        fi

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./docker # Указываем контекст сборки
        file: ./docker/nginx-app.dockerfile # Полный путь к dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/diploma-nginx-app:${{ env.TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/diploma-nginx-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
        kubectl cluster-info

    - name: Deploy to Kubernetes
      run: |
        # Обновляем образ в манифесте
        sed -i "s|image: aaborovik/diploma-nginx-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/diploma-nginx-app:${{ env.TAG }}|g" app/app-deployment.yml
        kubectl apply -f app/app-deployment.yml
        kubectl rollout status deployment/diploma-app -n app
        kubectl get pods -n app