name: Deploy to Kubernetes

on:
  push:
    tags:
    - 'v*' # Срабатывает при создании тега вида v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push tagged image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./nginx-app.dockerfile
        push: true
        tags: |
          ${{ vars.REGISTRY }}:${{ env.TAG }}  # Образ с тегом v1.0.0
          ${{ vars.REGISTRY }}:latest          # Образ с тегом latest

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        kubectl cluster-info

    - name: Deploy to Kubernetes
      run: |
        # Подставляем тег в манифест и применяем
        sed -i "s|image: aaborovik/diploma-app:.*|image: ${{ vars.REGISTRY }}:${{ env.TAG }}|g" app-deployment.yml
        kubectl apply -f app-deployment.yml
        kubectl rollout status deployment/diploma-app -n app
