name: Terraform Apply

on:
  push:
    branches:
    - main
    paths:
    - 'terraform/infrastruct/**'
    # - 'terraform/infrastruct/*.tfvars'
    # - 'terraform/infrastruct/templates/**'
    # - 'terraform/infrastruct/modules/**'

env:
  TF_VERSION: "1.11.4"
  YC_CLOUD_ID: ${{ secrets.CLOUD_ID }}
  YC_FOLDER_ID: ${{ secrets.FOLDER_ID }}
  YC_TOKEN: ${{ secrets.TOKEN }}
  PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
  BUCKET_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  BUCKET_SECRET_KEY: ${{ secrets.SECRET_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/infrastruct

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: >
        terraform plan -input=false 
        -var="cloud_id=${{ env.YC_CLOUD_ID }}"
        -var="folder_id=${{ env.YC_FOLDER_ID }}"
        -var="token=${{ env.YC_TOKEN }}"
        -var="ssh_public_key=${{ env.PUBLIC_KEY }}"
        -var="bucket=${{ env.BUCKET_NAME }}"
        -var="access_key=${{ env.BUCKET_ACCESS_KEY }}"
        -var="secret_key=${{ env.BUCKET_SECRET_KEY }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - name: Upload Ansible Inventory as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ansible-inventory
        path: /tmp/diploma-inventory/inventory  # Путь из Terraform (для GitHub Actions)
        if-no-files-found: error  # Завершить с ошибкой, если файл не найден
